/**
 * Created by zhu on 2016/10/20.
 *
 */
const routers=[
    {
        path:'/',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index.vue'))//打包切割
            });
        }
    },
    {
        path:'/address',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/address.vue'))
            });
        }
    },
    {
        path:'/login',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/login.vue'))
            });
        }
    },
    {
        path:'/register',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/register.vue'))
            });
        }
    },
    {
        path:'/appointment',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/appointment.vue'))
            });
        }
    },
    {
        path:'/activityRegistration',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/activityRegistration.vue'))
            });
        }
    },
    {
        path:'/brand',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/brand.vue'))
            });
        }
    },
    {
        path:'/activityPage',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/activityPage.vue'))
            });
        }
    },
     {
        path:'/courseIntroduction',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/courseIntroduction.vue'))
            });
        }
    },
     {
        path:'/parentsMBA',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/parentsMBA.vue'))
            });
        }
    },
    {
        path:'/newsCenter',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/newsCenter.vue'))
            });
        }
    },
    {
        path:'/latestActivity',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/latestActivity.vue'))
            });
        }
    }
];
export default routers;
